name: mobile_p3l
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.2+1
  toastification: ^1.2.1
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.2.2
  salomon_bottom_bar: ^3.3.2
  page_transition: ^2.1.0
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  email_validator: ^2.0.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
